# -*- coding: utf-8 -*-
"""Main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Nx8cDsJ4gIV2te1Phm8MIPJ5PcexLJH
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from predictor.app import router as predictor_router
from bot.bot import router as bot_router
from Timetable.logic import router as timetable_router

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Dono ko "include" kar lo
app.include_router(predictor_router, prefix="/predict")
app.include_router(bot_router, prefix="/chat")
app.include_router(timetable_router,prefix="/timetable")
@app.api_route("/", methods=["GET", "HEAD"])
async def health_check():
    return {"status": "online"}
